---
when:
  - event: [ push, pull_request ]

steps:
  test:
    image: mcr.microsoft.com/dotnet/sdk:10.0.102-alpine3.23
    commands:
      - dotnet restore
      - dotnet build --no-restore --configuration Release
      - |
        # Run tests for all test projects with coverage
        for test_project in test/**/*.csproj; do
          echo "Running tests for $test_project"
          dotnet test "$test_project" --no-build --configuration Release --coverage --coverage-output-format cobertura
        done
      - dotnet tool install --global dotnet-reportgenerator-globaltool
      - export PATH="$PATH:/root/.dotnet/tools"
      - |
        # Find all coverage files from test projects
        COVERAGE_FILES=$(find test -name "coverage.cobertura.xml" -path "*/TestResults/*" | tr '\n' ';')
        echo "Found coverage files: $COVERAGE_FILES"

        # Generate merged coverage report
        reportgenerator \
          -reports:"$COVERAGE_FILES" \
          -targetdir:"./coverage-report" \
          -reporttypes:"TextSummary;Html"
      - cat ./coverage-report/Summary.txt
      - |
        # Extract line coverage percentage and check threshold
        LINE_COVERAGE=$(grep "Line coverage:" ./coverage-report/Summary.txt | grep -oP '\d+\.?\d*(?=%)')
        echo "Line coverage: ${LINE_COVERAGE}%"

        if (( $(echo "$LINE_COVERAGE < 80" | bc -l) )); then
          echo "❌ Error: Code coverage (${LINE_COVERAGE}%) is below the required 80% threshold"
          exit 1
        fi

        echo "✅ Code coverage meets threshold (${LINE_COVERAGE}% >= 80%)"
